version: "3.9"

services:
  app:
    build: .
    command: /usr/local/bin/wedding-save-the-date
    volumes:
      - "./static:/static"
    environment:
      - "POSTGRES_CONN_STRING=postgresql://wedding:mysecretpassword@db/wedding"
      - "CONTENT_ROOT=/static"
    depends_on:
      - db
    ports:
      - "3030:3030"

  db:
    image: 'postgres:14.4-alpine3.16'
    environment:
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_USER=wedding"
      - "PGDATA=/var/lib/postgresql/data/wedding"
    ports:
      - "5432:5432"
    volumes:
      # - "wedding_database:/var/lib/postgresql/data/wedding"
      - "./wedding_schema:/docker-entrypoint-initdb.d/"

  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"

volumes:
  wedding_database:
